import type { Portfolio, TagColors } from "../types/portfolio";

export const PORTFOLIO_INFO: Portfolio = {
  meta: {
    createdAt: new Date().toISOString(),
    locale: "en-US",
    url: "https://johnagboola.com",
    pdf: "/resume.pdf",
  },
  personal: {
    name: "John Babatunde AGBOOLA",
    title: "Senior Backend Developer | Full Stack Developer | Software Engineer",
    headline: "Java · Spring Boot · Python · Node.js · React · Microservices",
    avatar: "./profile.jpg",
    summary:
      "Senior Backend and Full Stack Engineer with 8+ years of experience building secure, scalable financial and enterprise systems across banking, fintech, and international e-commerce. Strong backend focus using Java (Spring Boot), Python, Node.js, and microservices architecture, with hands-on frontend and mobile experience in React, Angular, and React Native. Proven track record designing core banking systems, payment platforms, and high-availability APIs processing millions of transactions with 99.9%+ uptime. Experienced working with NIBSS, Interswitch, Stripe, Paystack, cloud infrastructure (AWS, GCP), and regulated environments. Comfortable collaborating with global teams across Nigeria, USA, and the UK.",
    contact: {
      email: "johnagboola73@gmail.com",
      phone: "+2349014639260",
      location: "Lagos, Nigeria",
      website: "https://johnagboola.com",
      socials: [
        {
          label: "LinkedIn",
          url: "https://linkedin.com/in/john-agboola-81a5a52a9",
          icon: "SiLinkedin",
        },
        {
          label: "GitHub",
          url: "https://github.com/bigjohncodes",
          icon: "SiGithub",
        },
      ],
    },
  },
  highlights: [
    "Senior Backend and Full Stack Engineer with 8+ years of experience",
    "Architected banking and fintech systems with millions of transactions and 99.9% uptime",
    "Experienced with NIBSS, Interswitch, Stripe, Paystack, AWS, and GCP",
  ],
  skills: [
    {
      title: "Languages",
      skills: [
        {
          name: "Java",
          level: 90,
          icon: "SiJava",
          category: "backend",
          years: 8,
          note: "Primary backend language, used extensively in banking systems",
        },
        {
          name: "Kotlin",
          level: 85,
          icon: "SiKotlin",
          category: "backend",
          years: 3,
          note: "Used in production since 2021",
        },
        {
          name: "Python",
          level: 88,
          icon: "SiPython",
          category: "backend",
          years: 6,
          note: "Used in production since 2018",
        },
        {
          name: "PHP",
          level: 85,
          icon: "SiPhp",
          category: "backend",
          years: 5,
          note: "Used in production since 2017",
        },
        {
          name: "JavaScript",
          level: 90,
          icon: "SiJavascript",
          category: "frontend",
          years: 8,
          note: "Used in production since 2016",
        },
        {
          name: "TypeScript",
          level: 85,
          icon: "SiTypescript",
          category: "frontend",
          years: 5,
          note: "Used in production since 2019",
        },
        {
          name: "Node.js",
          level: 88,
          icon: "SiNodedotjs",
          category: "backend",
          years: 6,
          note: "Used in production since 2018",
        },
      ],
    },
    {
      title: "Backend",
      skills: [
        {
          name: "Spring Boot",
          level: 92,
          icon: "SiSpring",
          category: "backend",
          years: 5,
          note: "Primary framework for banking and fintech systems",
        },
        {
          name: "Spring Security",
          level: 88,
          icon: "SiSpring",
          category: "backend",
          years: 5,
          note: "Security implementation for financial systems",
        },
        {
          name: "NestJS",
          level: 85,
          icon: "SiNestjs",
          category: "backend",
          years: 4,
          note: "Used in production since 2020",
        },
        {
          name: "Express",
          level: 85,
          icon: "SiExpress",
          category: "backend",
          years: 6,
          note: "Used in production since 2018",
        },
        {
          name: "FastAPI",
          level: 88,
          icon: "SiFastapi",
          category: "backend",
          years: 4,
          note: "Used in production since 2020",
        },
        {
          name: "Django",
          level: 85,
          icon: "SiDjango",
          category: "backend",
          years: 3,
          note: "Used in production since 2021",
        },
        {
          name: "Laravel",
          level: 88,
          icon: "SiLaravel",
          category: "backend",
          years: 5,
          note: "Used in production since 2017",
        },
      ],
    },
    {
      title: "Frontend",
      skills: [
        {
          name: "React",
          level: 88,
          icon: "SiReact",
          category: "frontend",
          years: 6,
          note: "Used in production since 2018",
        },
        {
          name: "Angular",
          level: 85,
          icon: "SiAngular",
          category: "frontend",
          years: 4,
          note: "Used in production since 2020",
        },
        {
          name: "Vue.js",
          level: 80,
          icon: "SiVuedotjs",
          category: "frontend",
          years: 3,
          note: "Used in production since 2019",
        },
        {
          name: "React Native",
          level: 82,
          icon: "SiReact",
          category: "frontend",
          years: 3,
          note: "Mobile app development",
        },
      ],
    },
    {
      title: "Databases",
      skills: [
        {
          name: "PostgreSQL",
          level: 90,
          icon: "SiPostgresql",
          category: "database",
          years: 6,
          note: "Primary database for banking and fintech systems",
        },
        {
          name: "MySQL",
          level: 88,
          icon: "SiMysql",
          category: "database",
          years: 8,
          note: "Used in production since 2016",
        },
        {
          name: "MongoDB",
          level: 85,
          icon: "SiMongodb",
          category: "database",
          years: 5,
          note: "Used in production since 2019",
        },
        {
          name: "Redis",
          level: 88,
          icon: "SiRedis",
          category: "database",
          years: 5,
          note: "Caching and session management",
        },
      ],
    },
    {
      title: "Cloud & DevOps",
      skills: [
        {
          name: "AWS",
          level: 88,
          icon: "SiAmazonaws",
          category: "devops",
          years: 6,
          note: "Used in production since 2018",
        },
        {
          name: "GCP",
          level: 85,
          icon: "SiGooglecloud",
          category: "devops",
          years: 3,
          note: "Used in production since 2021",
        },
        {
          name: "Docker",
          level: 90,
          icon: "SiDocker",
          category: "devops",
          years: 6,
          note: "Containerization for microservices",
        },
        {
          name: "Kubernetes",
          level: 85,
          icon: "SiKubernetes",
          category: "devops",
          years: 4,
          note: "Orchestration for production systems",
        },
        {
          name: "Helm",
          level: 80,
          icon: "SiHelm",
          category: "devops",
          years: 3,
          note: "Kubernetes package management",
        },
        {
          name: "GitHub Actions",
          level: 85,
          icon: "SiGithubactions",
          category: "devops",
          years: 4,
          note: "CI/CD pipelines",
        },
        {
          name: "Jenkins",
          level: 82,
          icon: "SiJenkins",
          category: "devops",
          years: 4,
          note: "CI/CD automation",
        },
      ],
    },
    {
      title: "Architecture & Tools",
      skills: [
        {
          name: "Microservices",
          level: 90,
          category: "other",
          years: 6,
          note: "Architected multiple microservices systems",
        },
        {
          name: "Kafka",
          level: 85,
          icon: "SiApachekafka",
          category: "other",
          years: 4,
          note: "Event streaming and messaging",
        },
        {
          name: "gRPC",
          level: 82,
          icon: "SiGrpc",
          category: "other",
          years: 3,
          note: "Inter-service communication",
        },
        {
          name: "REST",
          level: 92,
          category: "other",
          years: 8,
          note: "API design and implementation",
        },
        {
          name: "TDD",
          level: 85,
          category: "other",
          years: 5,
          note: "Test-driven development practices",
        },
        {
          name: "DDD",
          level: 80,
          category: "other",
          years: 4,
          note: "Domain-driven design",
        },
      ],
    },
    {
      title: "Payments & Integrations",
      skills: [
        {
          name: "NIBSS",
          level: 90,
          category: "other",
          years: 3,
          note: "Nigerian banking integration",
        },
        {
          name: "Interswitch",
          level: 90,
          category: "other",
          years: 4,
          note: "Payment gateway integration",
        },
        {
          name: "Paystack",
          level: 88,
          category: "other",
          years: 5,
          note: "Payment processing",
        },
        {
          name: "Stripe",
          level: 88,
          icon: "SiStripe",
          category: "other",
          years: 4,
          note: "International payment processing",
        },
        {
          name: "Shopify",
          level: 85,
          icon: "SiShopify",
          category: "other",
          years: 3,
          note: "E-commerce platform integration",
        },
      ],
    },
  ],
  experience: [
    {
      id: "davak-consult-2024",
      title: "Full Stack Developer / Team Lead",
      company: "Davak Consult",
      location: "Ondo, Nigeria (Remote)",
      date: { start: "2024-03", present: true },
      summary:
        "Lead end-to-end development of client platforms across e-commerce, healthcare, education, and events, acting as backend-first engineer and technical lead.",
      bullets: [
        "Architected and deployed 8+ production systems using containerized microservices and CI/CD pipelines, achieving 99.8% uptime.",
        "TiwaMart (E-commerce): Implemented payments, inventory, order processing, and multi-currency support serving 500+ DAU.",
        "EventHub: Built SaaS ticketing and payment system (Stripe, Paystack) processing 1,000+ bookings/month.",
        "University Portals: Developed university portal for both UNIMED and Wesley universities.",
        "Virtual Learning Platform (Thriveon): Developed CBT exams, progress tracking, and chatbot features supporting 2,000+ students.",
      ],
      tech: [
        "Python",
        "Node.js",
        "Laravel",
        "FastAPI",
        "PostgreSQL",
        "React",
        "Docker",
        "Kubernetes",
      ],
    },
    {
      id: "mcgrocer-2023",
      title: "Senior Full Stack Engineer",
      company: "McGrocer",
      location: "UK (Remote)",
      date: { start: "2023-02", end: "2024-12" },
      summary:
        "Integrated ERPNext and Shopify to scale an international e-commerce platform delivering groceries from UK retailers to 75+ countries.",
      bullets: [
        "Designed cloud infrastructure on GCP achieving 99.9% uptime and reducing costs by 30%.",
        "ERPNext—Shopify integration improving inventory accuracy by 85%.",
        "Automated shipping via ShipStation processing 3,000+ international shipments/month.",
      ],
      tech: [
        "Python",
        "Django",
        "ERPNext",
        "React",
        "GCP",
        "Frappe-Docker",
      ],
    },
    {
      id: "neptune-mfb-2021",
      title: "Senior Backend Engineer",
      company: "Neptune Microfinance Bank",
      location: "Lagos, Nigeria (Hybrid)",
      date: { start: "2021-02", end: "2024-02" },
      summary:
        "Developed mission-critical banking systems for a licensed microfinance bank, ensuring regulatory compliance and seamless integration with national payment infrastructure.",
      bullets: [
        "nVault App: Developed secure fintech application for intra/inter-bank transfers, serving 15,000+ users and processing $2M+ monthly transactions.",
        "Core Banking Application: Built core banking services handling 25,000+ customers and 500,000+ transactions/month with real-time reconciliation.",
        "Payment Integrations: Integrated NIBSS and Interswitch, processing 100,000+ transactions daily with 99.95% success rate.",
        "Implemented direct debit and investment platforms, improving collection efficiency by 45%.",
      ],
      tech: [
        "Spring Boot",
        "Kotlin",
        "Python",
        "FastAPI",
        "PostgreSQL",
        "Redis",
        "Docker",
        "Kubernetes",
        "Angular",
        "React",
        "React Native",
      ],
    },
    {
      id: "gurugeeks-2017",
      title: "Full Stack Web Developer",
      company: "Gurugeeks Royalty Limited",
      location: "Lagos, Nigeria & London, UK (Hybrid)",
      date: { start: "2017-09", end: "2020-11" },
      summary:
        "Led architecture and development of flagship enterprise platforms, driving digital transformation for SMEs and mid-sized organizations.",
      bullets: [
        "Led development of XCEL, a wholesale/retail/manufacturing platform serving 200+ businesses, improving operational efficiency by 40% through process automation and analytics.",
        "Designed and built Exceed (HRM & CRM) system automating payroll, HR workflows, and performance tracking for 1,000+ employees across multiple organizations.",
        "Migrated legacy CodeIgniter applications to Frappe ERPNext with zero downtime, improving system performance by 60% and reducing maintenance costs by 45%.",
        "Designed and deployed AWS cloud infrastructure achieving 99.95% availability, while reducing infrastructure costs by 35% through auto-scaling and resource optimization.",
      ],
      tech: [
        "PHP",
        "Laravel",
        "CodeIgniter",
        "Frappe",
        "ERPNext",
        "React",
        "Vue.js",
        "AWS",
        "Docker",
      ],
    },
    {
      id: "workspacetechub-2016",
      title: "Backend Developer",
      company: "Workspacetechub",
      location: "Lagos, Nigeria",
      date: { start: "2016-03", end: "2017-08" },
      summary:
        "Technology company delivering financial trading systems, payment services, and enterprise applications. Focused on building scalable, low-latency backend services for high-volume transaction systems.",
      bullets: [
        "Built backend services for financial trading platforms processing 50,000+ trades daily, achieving low-latency execution (<50ms) and supporting real-time risk analysis.",
        "Developed airtime and data payment microservices integrating Interswitch and Paystack, handling 20,000+ daily transactions with 99.8% success rate.",
        "Designed distributed inventory and order processing systems across 5+ warehouses, improving platform scalability by 300% and reducing order processing time.",
        "Implemented accounting, invoicing, and subscription billing systems, reducing financial errors by 70% through automation and validation rules.",
      ],
      tech: [
        "Java",
        "Spring Boot",
        "Python",
        "C++",
        "MySQL",
        "Nginx",
      ],
    },
  ],
  projects: [
    {
      id: "learn-algo",
      title: "Learn Algo",
      description: "Interactive visualizations that transform abstract concepts into intuitive understanding. Watch sorting, searching, and ML algorithms execute step-by-step.",
      tags: ["Algorithms", "DSA", "ML", "AI", "Visualization", "Next.js"],
      image: "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExYXpqYWFhbnBraWt3ZXhvajZsdjg5andyMGZzY2VibGg3bXE0MWxwayZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/2PuPWxuLV1FGyh03Ja/giphy.gif",
      href: "https://www.learn-algo.com",
      links: [
        {
          label: "GitHub",
          url: "https://github.com/satya00089/learn-algo",
          icon: "SiGithub",
        },
      ],
      isUnderDevelopment: true,
    },
    {
      id: "landing-zone-orchestrator",
      title: "Landing Zone Orchestrator",
      description: "A production-ready platform that transforms cloud infrastructure provisioning from manual IaC coding to an intuitive, form-driven workflow. Built with React, FastAPI, and MongoDB to generate validated Terraform templates for AWS, Azure, and GCP. Features include schema-driven form builder for VPC, Subnets, IAM, and networking resources, real-time Terraform code generation and validation, JWT-based authentication, MongoDB storage for projects and templates, and multi-cloud support.",
      tags: ["Terraform", "IaC", "React", "FastAPI", "MongoDB", "AWS", "Azure", "Full Stack"],
      image: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExZGtuYjY1emtsZmNjMXp1czdrdXR5bXE5ZDJheHVvZjY1azZxYnJieiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/qzImRjQVb2OUI84mTt/giphy.gif",
      href: "https://orchestrator.next-zen.dev",
      links: [
        {
          label: "GitHub",
          url: "https://github.com/satya00089/landing-zone-orchestrator-ui",
          icon: "SiGithub",
        },
      ],
      isUnderDevelopment: true,
    },
    {
      id: "diagrammatic",
      title: "Diagrammatic",
      description: "Diagrammatic (System Design Playground): A component library and living documentation for a design system.",
      tags: ["System Design", "Ai & ML", "React"],
      image: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExeTFnOGF3d3BodjFvY3NhanY5cnl5bmd4Z243aXB5M3hrOHg3d2tmeiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/WvzQektcJxs0oDFkHq/giphy.gif",
      href: "https://diagrammatic.next-zen.dev",
      links: [
        {
          label: "GitHub",
          url: "https://github.com/satya00089/diagrammatic",
          icon: "SiGithub",
        },
      ],
    },
    {
      id: "mui-color-wheel",
      title: "MUI Color Wheel",
      description:
        "A Material-UI based color wheel component with real-time color picking.",
      tags: ["React", "Material-UI", "NPM Package", "Storybook"],
      image:
        "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExYTJxYjhmdTVjam41aWlzczZreGZ2eXc5eThjdDRpMXgxYzVuYTAzMiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/tWnCyw4rmoFY8CmhLV/giphy.gif",
      href: "https://mui-color-wheel.vercel.app/",
      links: [
        {
          label: "Storybook",
          url: "https://mui-color-wheel.vercel.app/",
          icon: "SiStorybook",
        },
        {
          label: "NPM",
          url: "https://www.npmjs.com/package/mui-color-wheel",
          icon: "SiNpm",
        },
        {
          label: "GitHub",
          url: "https://github.com/satya00089/mui-color-wheel",
          icon: "SiGithub",
        },
      ],
      isUnderDevelopment: true,
    },
    {
      id: "alochona",
      title: "Alochona",
      description: "Alochona is an experimental chatbot hosted on Hugging Face Spaces. It uses OpenAI under the hood for responses. This project was built as a way to explore chatbot UIs, Hugging Face deployment, and integrating OpenAI APIs.",
      image:
        "https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExZmc5dDY1c2ZnOGs0ODF0eDkwbzBvMHZ2ZXJvYml2amRmdzN2dnZueSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/7AFQj6uviWpwudbOWg/giphy.gif",
      href: "https://huggingface.co/spaces/satya00089/alochona",
      links: [
        {
          label: "Huggingface",
          url: "https://huggingface.co/spaces/satya00089/alochona/tree/main",
          icon: "SiHuggingface",
        },
        {
          label: "GitHub",
          url: "https://github.com/satya00089/alochona",
          icon: "SiGithub",
        },
      ],
      tags: ["Chatbot", "OpenAI", "Hugging Face", "Beginner Project"],
    },
    {
      id: "night-sky",
      title: "Night Skyline",
      description: "A breathtaking recreation of the city skyline under a starlit night sky, capturing the serene beauty and glowing atmosphere of the evening.",
      tags: ["React", "CSS"],
      image:
        "https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExc2RjaHAxY3N3enY0d3RldWVpczg2ZTNzMHhsY2dpam0yYnp6bWh2byZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/P2jddT5c9g9OeHI17p/giphy.gif",
      href: "https://satya00089.github.io/night-sky",
      links: [
        {
          label: "Watch",
          url: "https://www.loom.com/share/1516014366e34135a67f5dd4e551fec5",
          icon: "FaPlay",
        },
        {
          label: "GitHub",
          url: "https://github.com/satya00089/night-sky",
          icon: "SiGithub",
        },
      ],
      isUnderDevelopment: true,
    },
    {
      id: "data-dashboard-poc",
      title: "Data Dashboard (POC)",
      description: "Real-time charts and alerts for operational metrics.",
      tags: ["React", "D3", "Realtime"],
      image: undefined,
      href: "#",
      isUnderDevelopment: true,
    },
  ],
  education: [
    {
      degree: "B.Ed., Counsellor Education",
      school: "University of Ilorin",
      date: "2017-2022",
    },
    {
      degree: "TEFL (Teaching English as a Foreign Language)",
      school: "China",
      date: "2021-2022",
    },
    {
      degree: "National Youth Service Corps (NYSC)",
      school: "Nigeria",
      date: "2023-2024",
    },
  ],
  certifications: [],
  extras: {
    languages: [{ name: "English", level: "Native" }],
    interests: ["astronomy", "music"],
  },
};



// ---------- SMALL HELPERS ----------
export const tagColors: TagColors = {
  React: "bg-blue-100 text-blue-800",
  CSS: "bg-teal-100 text-teal-800",
  CSS3: "bg-teal-100 text-teal-800",
  Tailwind: "bg-teal-100 text-teal-800",
  Stripe: "bg-purple-100 text-purple-800",
  "Design System": "bg-yellow-100 text-yellow-800",
  D3: "bg-amber-100 text-amber-800",
  Realtime: "bg-green-100 text-green-800",
  Storybook: "bg-pink-100 text-pink-800",
  "NPM Package": "bg-red-100 text-red-800",
  "Material-UI": "bg-indigo-100 text-indigo-800",
  "Chatbot": "bg-violet-100 text-violet-800",
  OpenAI: "bg-gray-100 text-gray-800",
  "Hugging Face": "bg-orange-100 text-orange-800",
  Beginner: "bg-cyan-100 text-cyan-800",
  "Beginner Project": "bg-cyan-100 text-cyan-800",
  // Landing Zone Orchestrator tags
  FastAPI: "bg-teal-500 text-white",
  MongoDB: "bg-green-600 text-white",
  Terraform: "bg-purple-600 text-white",
  IaC: "bg-indigo-500 text-white",
  AWS: "bg-orange-500 text-white",
  Azure: "bg-blue-600 text-white",
  "Full Stack": "bg-gradient-to-r from-blue-500 to-purple-600 text-white",
};